spellername = "Lower Sorbian"
spellerversion = "0.1.0"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Lower Sorbian spellchecker"
dsb = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Lower Sorbian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
dsb = "TRANSLATE: A spellchecker for Lower Sorbian, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.dsb"

[windows]
system_product_code = "{851C8222-C659-4556-BDE7-2A2DD35B9B0F}_is1"
