template = "https://github.com/giellalt/template-lang-und"
rev_id = 301
template_sha = "14c7684fb7ae87003fef7c476a4f619d2addefa7"

[replacements]
__GLOTTOLOG_ID__ = "lowe1385"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-dsb"
__UND2C__ = "dsb"
__UNDEFINED__ = "Lower Sorbian"
__UND__ = "dsb"
